export const enemies = [
  { id: 1, name: "Big Johninator", icon: ["https://ultrakill.wiki.gg/images/BigJohnator.webp"] },
  { id: 2, name: "Cancerous Rodent", icon: ["https://ultrakill.wiki.gg/images/Cancerous_Rodent.webp"] },
  { id: 3, name: "Very Cancerous Rodent", icon: ["https://ultrakill.wiki.gg/images/Very_Cancerous_Rodent.webp"] },
  { id: 4, name: "Cerberus", icon: ["https://ultrakill.wiki.gg/images/Cerberus.webp"] },
  { id: 5, name: "Deathcatcher", icon: ["https://ultrakill.wiki.gg/images/Deathcatcher.webp"] },
  { id: 6, name: "Drone", icon: ["https://ultrakill.wiki.gg/images/Drone.webp"] },
  { id: 7, name: "Earthmover (Central Brain)", icon: ["https://ultrakill.wiki.gg/images/Earthmover_Brain.png"] },
  { id: 8, name: "1000-THR Defence System (Mainframe)", icon: ["https://ultrakill.wiki.gg/images/Earthmover_Defence_Mainframe.png"] },
  { id: 9, name: "1000-THR Defence System (Rocket Launchers)", icon: ["https://ultrakill.wiki.gg/images/CentaurRocketLauncher.webp"] },
  { id: 10, name: "1000-THR Defence System (Mortar Launchers)", icon: ["https://ultrakill.wiki.gg/images/CentaurMortar.webp"] },
  { id: 11, name: "1000-THR Defence System (Towers)", icon: ["https://ultrakill.wiki.gg/images/CentaurTower.webp"] },
  { id: 12, name: "Ferryman", icon: ["https://ultrakill.wiki.gg/images/Ferryman.webp"] },
  { id: 13, name: "Filth", icon: ["https://ultrakill.wiki.gg/images/Filth.webp"] },
  { id: 14, name: "Flesh Panopticon", icon: ["https://ultrakill.wiki.gg/images/Flesh_Panopticon.webp"] },
  { id: 15, name: "Spotlight Eye Spawn", icon: ["https://ultrakill.wiki.gg/images/PanopticonEye.webp"] },
  { id: 16, name: "Malicious Spawn", icon: ["https://ultrakill.wiki.gg/images/Malicious_Face.webp"] },
  { id: 17, name: "Flesh Prison", icon: ["https://ultrakill.wiki.gg/images/Flesh_Prison.webp"] },
  { id: 18, name: "Eye Spawn", icon: ["https://ultrakill.wiki.gg/images/FleshPrisonEye.webp"] },
  { id: 19, name: "Malicious Spawn (P1)", icon: ["https://ultrakill.wiki.gg/images/Malicious_Face.webp"] },
  { id: 20, name: "Gabriel (Judge of Hell)", icon: ["https://ultrakill.wiki.gg/images/Gabriel%2C_Judge_of_Hell.webp"] },
  { id: 21, name: "Gabriel (Apostate of Hate)", icon: ["https://ultrakill.wiki.gg/images/Gabriel%2C_Apostate_of_Hate.webp"] },
  { id: 22, name: "Geryon", icon: ["https://ultrakill.wiki.gg/images/Geryon.webp"] },
  { id: 23, name: "Gutterman", icon: ["https://ultrakill.wiki.gg/images/Gutterman.webp"] },
  { id: 24, name: "Guttertank", icon: ["https://ultrakill.wiki.gg/images/Guttertank.webp"] },
  { id: 25, name: "Hideous Mass", icon: ["https://ultrakill.wiki.gg/images/Hideous_Mass.webp"] },
  { id: 26, name: "Idol", icon: ["https://ultrakill.wiki.gg/images/Idol.webp"] },
  { id: 27, name: "Insurrectionist", icon: ["https://ultrakill.wiki.gg/images/Insurrectionist.webp"] },
  { id: 28, name: "Leviathan", icon: ["https://ultrakill.wiki.gg/images/Leviathan.webp"] },
  { id: 29, name: "Malicious Face", icon: ["https://ultrakill.wiki.gg/images/Malicious_Face.webp"] },
  { id: 30, name: "Mannequin", icon: ["https://ultrakill.wiki.gg/images/Mannequin.webp"] },
  { id: 31, name: "Mindflayer", icon: ["https://ultrakill.wiki.gg/images/Mindflayer.webp"] },
  { id: 32, name: "Minos Prime", icon: ["https://ultrakill.wiki.gg/images/Minos_Prime.webp"] },
  { id: 33, name: "Minotaur", icon: ["https://ultrakill.wiki.gg/images/Minotaur.webp"] },
  { id: 34, name: "Mirror Reaper", icon: ["https://ultrakill.wiki.gg/images/Mirror_Reaper.webp"] },
  { id: 35, name: "Mysterious Druid Knight (& Owl)", icon: ["https://ultrakill.wiki.gg/images/Mysterious_Druid_Knight_%28%26_Owl%29.webp"] },
  { id: 36, name: "Power", icon: ["https://ultrakill.wiki.gg/images/Power.webp"] },
  { id: 37, name: "Providence", icon: ["https://ultrakill.wiki.gg/images/Providence.webp"] },
  { id: 38, name: "Puppet", icon: ["https://ultrakill.wiki.gg/images/Puppet.webp"] },
  { id: 39, name: "Schism", icon: ["https://ultrakill.wiki.gg/images/Schism.webp"] },
  { id: 40, name: "Sentry", icon: ["https://ultrakill.wiki.gg/images/Sentry.webp"] },
  { id: 41, name: "Sisyphus Prime", icon: ["https://ultrakill.wiki.gg/images/Sisyphus_Prime.webp"] },
  { id: 42, name: "Soldier", icon: ["https://ultrakill.wiki.gg/images/Soldier.webp"] },
  { id: 43, name: "Something Wicked", icon: ["https://ultrakill.wiki.gg/images/Something_Wicked.webp"] },
  { id: 44, name: "Stalker", icon: ["https://ultrakill.wiki.gg/images/Stalker.webp"] },
  { id: 45, name: "Stray", icon: ["https://ultrakill.wiki.gg/images/Stray.webp"] },
  { id: 46, name: "Streetcleaner", icon: ["https://ultrakill.wiki.gg/images/Streetcleaner.webp"] },
  { id: 47, name: "Swordsmachine", icon: ["https://ultrakill.wiki.gg/images/Swordsmachine.webp"] },
  { id: 50, name: "The Corpse of King Minos' Arm", icon: ["https://ultrakill.wiki.gg/images/MinosArmFull.png"] },
  { id: 51, name: "The Corpse of King Minos", icon: ["https://ultrakill.wiki.gg/images/The_Corpse_of_King_Minos.webp"] },
  { id: 52, name: "V2", icon: ["https://ultrakill.wiki.gg/images/V2.webp"] },
  { id: 53, name: "V2 (2nd)", icon: ["https://ultrakill.wiki.gg/images/V2_%282nd%29.webp"] },
  { id: 54, name: "Virtue", icon: ["https://ultrakill.wiki.gg/images/Virtue.webp"] },
  { id: 59, name: "Ghost Drone", icon: ["https://ultrakill.wiki.gg/images/Drone.webp"] },
  {
    id: 66,
    name: 'Swordsmachine "Tundra/Agony"',
    icon: ["https://ultrakill.wiki.gg/images/Swordsmachine_%22Tundra%22.webp", "https://ultrakill.wiki.gg/images/Swordsmachine_%22Agony%22.webp"],
  },
  {
    id: 67,
    name: 'Insurrectionist "Angry/Rude"',
    icon: ["https://ultrakill.wiki.gg/images/Angry.png", "https://ultrakill.wiki.gg/images/Rude.png"],
  },
  {
    id: 68,
    name: 'Ferryman "Rudraksha/Agonis"',
    icon: ["https://ultrakill.wiki.gg/images/Ferryman.webp", "https://ultrakill.wiki.gg/images/Ferryman.webp"],
  },
];
