export const enemies = [
  { id: 1, name: "Big Johninator" },
  { id: 2, name: "Cancerous Rodent" },
  { id: 3, name: "Very Cancerous Rodent" },
  { id: 4, name: "Cerberus" },
  { id: 5, name: "Deathcatcher" },
  { id: 6, name: "Drone" },
  { id: 7, name: "Earthmover (Central Brain)" },
  { id: 8, name: "1000-THR Defence System (Mainframe)" },
  { id: 9, name: "1000-THR Defence System (Rocket Launchers)" },
  { id: 10, name: "1000-THR Defence System (Mortar Launchers)" },
  { id: 11, name: "1000-THR Defence System (Towers)" },
  { id: 12, name: "Ferryman" },
  { id: 13, name: "Filth" },
  { id: 14, name: "Flesh Panopticon" },
  { id: 15, name: "Spotlight Eye Spawn" },
  { id: 16, name: "Malicious Spawn" },
  { id: 17, name: "Flesh Prison" },
  { id: 18, name: "Eye Spawn" },
  { id: 19, name: "Malicious Spawn (P1)" },
  { id: 20, name: "Gabriel (Judge of Hell)" },
  { id: 21, name: "Gabriel (Apostate of Hate)" },
  { id: 22, name: "Geryon" },
  { id: 23, name: "Gutterman" },
  { id: 24, name: "Guttertank" },
  { id: 25, name: "Hideous Mass" },
  { id: 26, name: "Idol" },
  { id: 27, name: "Insurrectionist" },
  { id: 28, name: "Leviathan" },
  { id: 29, name: "Malicious Face" },
  { id: 30, name: "Mannequin" },
  { id: 31, name: "Mindflayer" },
  { id: 32, name: "Minos Prime" },
  { id: 33, name: "Minotaur" },
  { id: 34, name: "Mirror Reaper" },
  { id: 35, name: "Mysterious Druid Knight (& Owl)" },
  { id: 36, name: "Power" },
  { id: 37, name: "Providence" },
  { id: 38, name: "Puppet" },
  { id: 39, name: "Schism" },
  { id: 40, name: "Sentry" },
  { id: 41, name: "Sisyphus Prime" },
  { id: 42, name: "Soldier" },
  { id: 43, name: "Something Wicked" },
  { id: 44, name: "Stalker" },
  { id: 45, name: "Stray" },
  { id: 46, name: "Streetcleaner" },
  { id: 47, name: "Swordsmachine" },
  { id: 48, name: "Swordsmachine \"Agony\"" },
  { id: 49, name: "Swordsmachine \"Tundra\"" },
  { id: 50, name: "The Corpse of King Minos' Arm" },
  { id: 51, name: "The Corpse of King Minos" },
  { id: 52, name: "V2" },
  { id: 53, name: "V2 (2nd)" },
  { id: 54, name: "Virtue" },
];
