
[functions.discord-token]
enabled = true
verify_jwt = true
import_map = "./functions/discord-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/discord-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/discord-token/*.html" ]

[functions.discord-bot]
enabled = true
verify_jwt = true
import_map = "./functions/discord-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/discord-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/discord-bot/*.html" ]

[functions.daily-message]
enabled = true
verify_jwt = true
import_map = "./functions/daily-message/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/daily-message/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/daily-message/*.html" ]

[functions.poll-submissions]
enabled = true
verify_jwt = true
import_map = "./functions/poll-submissions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/poll-submissions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/poll-submissions/*.html" ]

[functions.inferno-daily-setup]
enabled = true
verify_jwt = true
import_map = "./functions/inferno-daily-setup/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/inferno-daily-setup/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/inferno-daily-setup/*.html" ]

[functions.kofi-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/kofi-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/kofi-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/kofi-webhook/*.html" ]

[functions.dispatch-daily]
enabled = true
verify_jwt = true
import_map = "./functions/dispatch-daily/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispatch-daily/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispatch-daily/*.html" ]

[functions.send-daily-result]
enabled = true
verify_jwt = true
import_map = "./functions/send-daily-result/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-daily-result/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-daily-result/*.html" ]

[functions.dispatch-submissions]
enabled = true
verify_jwt = true
import_map = "./functions/dispatch-submissions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispatch-submissions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispatch-submissions/*.html" ]

[functions.ingest-worker]
enabled = true
verify_jwt = true
import_map = "./functions/ingest-worker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ingest-worker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ingest-worker/*.html" ]

[functions.resolve-worker]
enabled = true
verify_jwt = true
import_map = "./functions/resolve-worker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resolve-worker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resolve-worker/*.html" ]

[functions.refetch-submitters-data]
enabled = true
verify_jwt = true
import_map = "./functions/refetch-submitters-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/refetch-submitters-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/refetch-submitters-data/*.html" ]

[functions.optimized-daily-message]
enabled = true
verify_jwt = true
import_map = "./functions/optimized-daily-message/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/optimized-daily-message/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/optimized-daily-message/*.html" ]

[functions.rate-limited-daily-message]
enabled = true
verify_jwt = true
import_map = "./functions/rate-limited-daily-message/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/rate-limited-daily-message/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/rate-limited-daily-message/*.html" ]
